#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#!/bin/sh
red='\033[0;31m'



if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
    echo "🔨❌${red} Aborting commit. Your commit message is too long.🔨❌" >&2
    exit 1
fi